name: Build compositions.json

on:
  push:
    paths:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate compositions.json
        run: |
          node <<'EOF'
          const fs = require('fs');
          const path = require('path');

          const docsDir = path.join(process.cwd(), 'docs');
          const categories = {};

          /**
           * Recursively collect all PDFs inside a given folder.
           * @param {string} dir - Directory to scan
           * @returns {string[]} Array of relative PDF paths
           */
          function collectPdfs(dir) {
            let results = [];
            fs.readdirSync(dir).forEach(item => {
              const fullPath = path.join(dir, item);
              const relPath = path.relative(docsDir, fullPath);
              const stat = fs.lstatSync(fullPath);

              if (stat.isDirectory()) {
                results = results.concat(collectPdfs(fullPath));
              } else if (stat.isFile() && item.toLowerCase().endsWith('.pdf')) {
                results.push(relPath.replace(/\\/g, '/')); // normalize for Windows paths
              }
            });
            return results;
          }

          fs.readdirSync(docsDir).forEach(folder => {
            const fullPath = path.join(docsDir, folder);
            if (fs.lstatSync(fullPath).isDirectory()) {
              const pdfs = collectPdfs(fullPath);
              if (pdfs.length > 0) {
                categories[folder] = pdfs;
              }
            }
          });

          fs.writeFileSync(
            path.join(process.cwd(), 'compositions.json'),
            JSON.stringify(categories, null, 2)
          );
          EOF

      - name: Commit and push compositions.json
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add compositions.json
          git commit -m "Update compositions.json" || echo "No changes to commit"
          git push
